name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Validate OpenAPI spec
        run: |
          npm install -g @apidevtools/swagger-cli
          swagger-cli validate backend/openapi.yaml
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install Composer dependencies
        working-directory: backend
        run: composer install --no-interaction --prefer-dist
      - name: Prepare environment
        working-directory: backend
        run: |
          cp .env.example .env
          php artisan key:generate
      - name: Run tests
        working-directory: backend
        run: php artisan test
